<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Postman_Test" tests="3" time="0.000">
  <testsuite name="login" id="7f697579-ab0a-4cf7-bd12-e7130239a082" timestamp="2024-11-11T13:22:11.858Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1685:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

---
]]></system-err>
  </testsuite>
  <testsuite name="signup" id="7ce8dda0-43ae-42ec-983b-e2ed81e64861" timestamp="2024-11-11T13:22:11.858Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1685:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

---
]]></system-err>
  </testsuite>
  <testsuite name="Employee login" id="22f9e35f-fe99-47c1-8669-efa4d3c13a32" timestamp="2024-11-11T13:22:11.858Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1685:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

---
]]></system-err>
  </testsuite>
</testsuites>