<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Postman_Test" tests="3" time="0.000">
  <testsuite name="login" id="7512242c-9371-408f-aa8d-0f8e2da468d9" timestamp="2024-11-11T13:06:21.213Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1685:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

---
]]></system-err>
  </testsuite>
  <testsuite name="signup" id="0c48ec66-e2fb-4962-8e27-0d1662cd52da" timestamp="2024-11-11T13:06:21.213Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1685:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

---
]]></system-err>
  </testsuite>
  <testsuite name="Employee login" id="6e57da38-1933-4abf-92a9-f0c5b27c33b5" timestamp="2024-11-11T13:06:21.213Z" tests="0" failures="0" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1685:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

---
]]></system-err>
  </testsuite>
</testsuites>